#!/bin/sh
# Linksys WRT1900AC v2 / ImmortalWrt 24.10.6
# 广西联通 PPPoE + DHCPv6-PD/60 + 双频WiFi + FullCone + SFO + SYN-flood + UPnP
# + 主机名/密码/NTP(阿里+腾讯)/中文/Argon + LAN IP/DNS/DHCP池
# + WAN 锁 eth1 / keepalive / SSH-SCP 放行 / dropbear 显式配置

# ==================== 系统 ====================
uci set system.@system[0].hostname='WRT1900ACv2'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

# root 密码（交互式写入，比 chpasswd 在 uci-defaults 里更可靠）
/usr/bin/passwd root <<'PWD'
rootpassword
rootpassword
PWD

uci set luci.main.lang='zh-cn'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

uci delete system.ntp.server 2>/dev/null
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time2.cloud.tencent.com'
uci set system.ntp.enabled='1'
uci set system.ntp.enable_server='0'
uci commit system

# ==================== 清旧 wan6 ====================
uci delete network.wan6 2>/dev/null

# ==================== 1. WAN PPPoE ====================
uci set network.wan.proto='pppoe'
uci set network.wan.device='eth1'
uci set network.wan.username='77145396804'
uci del network.wan.password
uci set network.wan.password='396804'
uci set network.wan.mtu='1492'
uci set network.wan.keepalive='30 5'
uci set network.wan.ipv6='1'
uci set network.wan.peerdns='0'
uci del network.wan.dns 2>/dev/null
uci add_list network.wan.dns='223.5.5.5'
uci add_list network.wan.dns='119.29.29.29'
uci add_list network.wan.dns='2408:8888::8'
uci add_list network.wan.dns='2408:8000::8'
uci set network.wan.delegate='1'

# ==================== 2. wan6 DHCPv6-PD ====================
uci set network.wan6='interface'
uci set network.wan6.proto='dhcpv6'
uci set network.wan6.device='@wan'
uci set network.wan6.reqaddress='try'
uci set network.wan6.reqprefix='auto'
uci set network.wan6.delegate='1'
uci set network.wan6.zone='wan'

# ==================== 3. LAN IP / IPv6 下发 ====================
uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.ip6assign='60'
uci set network.lan.ip6class='wan6'
uci set network.lan.delegate='1'
uci set network.globals.packet_steering='1'
uci commit network

# ==================== 4. DHCP 池 + 下发 DNS ====================
uci set dhcp.lan.start='101'
uci set dhcp.lan.limit='99'
uci set dhcp.lan.leasetime='24h'
uci del dhcp.lan.dhcp_option 2>/dev/null
uci add_list dhcp.lan.dhcp_option='6,223.5.5.5,119.29.29.29'
uci set dhcp.lan.ra='server'
uci set dhcp.lan.ra_slaac='1'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra_default='1'
uci set dhcp.lan.ra_management='1'
uci commit dhcp

# ==================== 5. 无线 ====================
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='CN'
uci set wireless.radio0.channel='161'
uci set wireless.radio0.htmode='VHT80'
uci set wireless.default_radio0.mode='ap'
uci set wireless.default_radio0.network='lan'
uci set wireless.default_radio0.ssid='22B013-5G'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='FeiNanBjCat'
uci set wireless.default_radio0.disabled='0'

uci set wireless.radio1.disabled='0'
uci set wireless.radio1.country='CN'
uci set wireless.radio1.channel='6'
uci set wireless.radio1.htmode='HT40'
uci set wireless.default_radio1.mode='ap'
uci set wireless.default_radio1.network='lan'
uci set wireless.default_radio1.ssid='CU_22B1013'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='FeiNanBjCat'
uci set wireless.default_radio1.disabled='0'
uci commit wireless

# ==================== 6. 防火墙 ====================
uci set firewall.@defaults[0].input='REJECT'
uci set firewall.@defaults[0].output='ACCEPT'
uci set firewall.@defaults[0].forward='REJECT'
uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='0'
uci set firewall.@defaults[0].syn_flood='1'
uci set firewall.@defaults[0].synflood_rate='200'
uci set firewall.@defaults[0].synflood_burst='200'
uci set firewall.@defaults[0].tcp_syncookies='1'

uci set firewall.wan.masq='1'
uci set firewall.wan.fullcone='1'
uci set firewall.wan.mtu_fix='1'
uci set firewall.wan.input='REJECT'
uci set firewall.wan.forward='REJECT'
uci set firewall.wan.output='ACCEPT'

# LAN 放行 SSH（SCP 也走 22）
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-SSH-LAN'
uci set firewall.@rule[-1].src='lan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='22'
uci set firewall.@rule[-1].target='ACCEPT'
uci commit firewall

# ==================== dropbear 显式配置 ====================
uci set dropbear.@dropbear[0].enable='1'
uci set dropbear.@dropbear[0].Port='22'
uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].RootPasswordAuth='on'
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

# ==================== 7. UPnP ====================
uci set upnpd.config.enabled='1'
uci set upnpd.config.enable_upnp='1'
uci set upnpd.config.enable_natpmp='1'
uci commit upnpd

# ==================== 8. 重启服务 ====================
wifi reload
/etc/init.d/sysntpd restart 2>/dev/null
/etc/init.d/network restart
/etc/init.d/odhcpd restart
/etc/init.d/firewall restart
/etc/init.d/miniupnpd enable 2>/dev/null
/etc/init.d/miniupnpd restart 2>/dev/null
/etc/init.d/dnsmasq restart 2>/dev/null
/etc/init.d/dropbear restart 2>/dev/null
/etc/init.d/uhttpd restart 2>/dev/null

exit 0
